[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
[environments.production.variables]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
REDIS_URL = "redis://localhost:6379/0"
LOG_LEVEL = "INFO"
WEBHOOK_TIMEOUT = "30"
WEBHOOK_RETRY_ATTEMPTS = "3"
SESSION_TTL_SECONDS = "172800"
MAX_FILE_SIZE_MB = "20"
MAX_FILES_PER_SESSION = "10"
MAX_STORAGE_PER_SESSION_MB = "200"
MAX_CONCURRENT_JOBS_PER_SESSION = "3"
CLEANUP_INTERVAL_MINUTES = "60"

[environments.staging]
[environments.staging.variables]
FLASK_ENV = "development"
PYTHONUNBUFFERED = "1"
REDIS_URL = "redis://localhost:6379/0"
LOG_LEVEL = "DEBUG"
WEBHOOK_TIMEOUT = "30"
WEBHOOK_RETRY_ATTEMPTS = "3"
SESSION_TTL_SECONDS = "86400"
MAX_FILE_SIZE_MB = "10"
MAX_FILES_PER_SESSION = "5"
MAX_STORAGE_PER_SESSION_MB = "100"
MAX_CONCURRENT_JOBS_PER_SESSION = "2"
CLEANUP_INTERVAL_MINUTES = "30" 