[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.worker"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# Pre-deploy command to clean Redis queue
preDeployCommand = "python pre-deploy-worker.py"

[environments.production.variables]
FLASK_ENV = "production"
LOG_LEVEL = "INFO"
PYTHONUNBUFFERED = "1" 