[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.worker"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# Pre-deploy command to clean Redis queue
preDeployCommand = "python pre-deploy-worker.py"
# Override incorrect start command
startCommand = "python -m src.worker"
# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 60

[environments.production.variables]
FLASK_ENV = "production"
LOG_LEVEL = "INFO"
PYTHONUNBUFFERED = "1" 