[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Production environment for main app
[environments.production]
[environments.production.variables]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
SECRET_KEY = "change-this-to-a-secure-random-key-in-production"
# Railway will inject REDIS_URL automatically when Redis service is connected
LOG_LEVEL = "INFO"
WEBHOOK_TIMEOUT = "30"
WEBHOOK_RETRY_ATTEMPTS = "3"
SESSION_TTL_SECONDS = "172800"
MAX_FILE_SIZE_MB = "20"
MAX_FILES_PER_SESSION = "10"
MAX_STORAGE_PER_SESSION_MB = "200"
MAX_CONCURRENT_JOBS_PER_SESSION = "3"
CLEANUP_INTERVAL_MINUTES = "60"
# Railway injects PORT automatically, but set fallback
FLASK_PORT = "5001"
FLASK_HOST = "0.0.0.0"
SECURE_HEADERS = "true"

[environments.staging]
[environments.staging.variables]
FLASK_ENV = "development"
PYTHONUNBUFFERED = "1"
SECRET_KEY = "development-key-not-secure"
LOG_LEVEL = "DEBUG"
WEBHOOK_TIMEOUT = "10"
WEBHOOK_RETRY_ATTEMPTS = "2"
SESSION_TTL_SECONDS = "3600"
MAX_FILE_SIZE_MB = "10"
MAX_FILES_PER_SESSION = "5"
MAX_STORAGE_PER_SESSION_MB = "50"
MAX_CONCURRENT_JOBS_PER_SESSION = "2"
CLEANUP_INTERVAL_MINUTES = "30"
FLASK_PORT = "5001"
FLASK_HOST = "0.0.0.0" 