[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.worker"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
FLASK_ENV = "production"
LOG_LEVEL = "INFO"
PYTHONUNBUFFERED = "1" 